"""Theme lexicon for the procedural families (randbn, randhmm).

Each domain has a `case` noun (the repeated unit: a match, a deployment, a survey plot, ...), instance-level
`globals` concepts and per-case concepts. Concepts are "noun phrase|state1,state2[,state3[,state4]]".
Placeholders: {X} = an invented proper name (fresh per concept), {c} = the case reference ("this match", "the
match", "the next match"). Invented names keep world knowledge from substituting for the stated numbers.
"""
from __future__ import annotations

from .common import pick

SYLL = ["ka", "lo", "ven", "tar", "mi", "sor", "qua", "bel", "dri", "no", "vex", "ul", "tha", "rim", "zo", "pel",
        "gar", "ish", "mon", "tev", "ra", "sel", "fen", "dor", "ki", "wyn", "osh", "bra", "lin", "cor", "ta", "e"]


def pseudo(rng, n=None) -> str:
    n = n or int(rng.integers(2, 4))
    w = "".join(pick(rng, SYLL) for _ in range(n))
    return w[:1].upper() + w[1:]


D = dict  # shorthand

DOMAINS = [
    D(name="ecology", case="survey plot", setting="the {X} wetland reserve",
      g=["the {X} frog population|declining,stable,growing", "the water acidity of {X} Pond|low,normal,high",
         "the {X} heron colony's health|poor,good", "this season's rainfall|dry,average,wet"],
      p=["the frog count in {c}|low,high", "the algae cover in {c}|sparse,moderate,dense",
         "whether heron tracks are found in {c}|found,not found", "the insect density in {c}|low,medium,high"]),
    D(name="finance", case="trading day", setting="the {X} commodities exchange",
      g=["the {X} fund's strategy|cautious,balanced,aggressive", "the regulator's stance|lenient,strict",
         "the market regime|calm,volatile", "the {X} bank's liquidity|tight,ample"],
      p=["the {X} index move on {c}|down,flat,up", "the trading volume on {c}|light,normal,heavy",
         "whether a margin call happens on {c}|margin call,no margin call", "the spread on {c}|narrow,wide"]),
    D(name="sports", case="match", setting="the {X} handball league",
      g=["the {X} Rovers' form|poor,average,strong", "the coach's tactic|defensive,attacking",
         "the star player's fitness|injured,fit", "the pitch quality at {X} Park|poor,good"],
      p=["the result of {c}|loss,draw,win", "the number of goals in {c}|few,many",
         "the crowd size at {c}|small,medium,large", "whether a red card is shown in {c}|red card,no red card"]),
    D(name="software", case="deployment", setting="the {X} payments service",
      g=["the code quality of the {X} module|poor,fair,good", "the test coverage|low,high",
         "the on-call engineer's experience|junior,senior", "the database version|old,current"],
      p=["the error rate after {c}|normal,elevated,critical", "whether {c} is rolled back|rolled back,kept",
         "the latency after {c}|fast,slow", "the pager alerts during {c}|none,some,many"]),
    D(name="astronomy", case="observing night", setting="the {X} observatory",
      g=["the {X} star's variability class|quiet,pulsing,eruptive", "the telescope calibration|off,good",
         "the dust level in the {X} nebula|thin,thick", "the companion object|absent,present"],
      p=["the brightness measured on {c}|dim,normal,bright", "the seeing on {c}|poor,fair,excellent",
         "whether a flare is recorded on {c}|flare,no flare", "the spectrum shift on {c}|blue,none,red"]),
    D(name="cooking", case="batch", setting="the {X} bakery",
      g=["the {X} flour supplier's grade|coarse,standard,fine", "the oven's calibration|cool,accurate,hot",
         "the starter culture|weak,vigorous", "the head baker's mood|rushed,careful"],
      p=["the rise of {c}|flat,good,excellent", "the crust of {c}|pale,golden,burnt",
         "whether {c} passes tasting|passes,fails", "the moisture of {c}|dry,moist"]),
    D(name="agriculture", case="field", setting="the {X} cooperative farm",
      g=["the soil type at {X} Farm|sandy,loamy,clay", "the irrigation policy|sparse,generous",
         "the {X} blight's presence|absent,present", "the seed variety|heritage,hybrid"],
      p=["the yield of {c}|poor,average,bumper", "the leaf colour in {c}|yellow,green",
         "the weed pressure in {c}|low,high", "whether pests are found in {c}|pests,no pests"]),
    D(name="shipping", case="voyage", setting="the {X} freight line",
      g=["the {X} vessel's hull condition|worn,sound", "the route choice|coastal,open-sea,canal",
         "the crew's training|basic,advanced", "the fuel contract|cheap,premium"],
      p=["the arrival of {c}|early,on time,late", "the cargo damage on {c}|none,minor,major",
         "the fuel use on {c}|low,high", "whether {c} meets a storm|storm,no storm"]),
    D(name="healthcare_ops", case="shift", setting="the {X} district hospital",
      g=["the staffing level|short,adequate,generous", "the {X} ward's flu status|clear,outbreak",
         "the triage protocol|old,new", "the equipment budget|tight,ample"],
      p=["the waiting time during {c}|short,moderate,long", "the number of admissions in {c}|few,many",
         "whether an incident is reported in {c}|incident,no incident", "the bed occupancy in {c}|low,high"]),
    D(name="education", case="exam", setting="the {X} academy",
      g=["the {X} teacher's method|lecture,workshop,project", "the class's prior preparation|weak,strong",
         "the textbook edition|old,new", "the school's funding|low,high"],
      p=["the average grade on {c}|fail,pass,merit,distinction", "the attendance at {c}|low,high",
         "whether cheating is detected in {c}|detected,not detected", "the difficulty of {c}|easy,hard"]),
    D(name="geology", case="core sample", setting="the {X} basin survey",
      g=["the rock formation under {X} Ridge|sandstone,shale,granite", "the {X} fault's activity|dormant,active",
         "the groundwater level|low,high", "the ore deposit|absent,present"],
      p=["the mineral content of {c}|trace,moderate,rich", "the porosity of {c}|low,high",
         "whether {c} shows fractures|fractured,intact", "the colour of {c}|grey,red,black"]),
    D(name="retail", case="week", setting="the {X} department store",
      g=["the {X} brand's popularity|fading,steady,rising", "the pricing strategy|discount,premium",
         "the store layout|old,renovated", "the local economy|slow,booming"],
      p=["the sales in {c}|low,medium,high", "the footfall in {c}|light,heavy",
         "whether stock runs out in {c}|stockout,no stockout", "the returns in {c}|few,many"]),
    D(name="music", case="concert", setting="the {X} chamber orchestra",
      g=["the conductor's style|restrained,expressive", "the {X} violinist's form|off,good,brilliant",
         "the hall acoustics|dry,resonant", "the rehearsal time|short,long"],
      p=["the review of {c}|negative,mixed,positive", "the ticket sales for {c}|poor,good",
         "whether {c} gets an encore|encore,no encore", "the tempo in {c}|slow,brisk"]),
    D(name="aviation", case="flight", setting="the {X} regional airline",
      g=["the {X} aircraft's maintenance state|overdue,current", "the pilot roster|thin,full",
         "the hub airport's congestion|low,medium,high", "the season|winter,summer"],
      p=["the departure of {c}|on time,delayed,cancelled", "the turbulence on {c}|smooth,bumpy",
         "the load factor of {c}|low,high", "whether {c} diverts|diverted,not diverted"]),
    D(name="beekeeping", case="hive inspection", setting="the {X} apiary",
      g=["the {X} queen's vigour|failing,average,strong", "the mite load|low,high",
         "the forage supply|scarce,plentiful", "the colony temperament|calm,defensive"],
      p=["the brood pattern at {c}|spotty,solid", "the honey stores at {c}|low,medium,high",
         "whether swarm cells are seen at {c}|seen,not seen", "the bee activity at {c}|quiet,busy"]),
    D(name="energy", case="day", setting="the {X} grid region",
      g=["the {X} plant's efficiency|low,medium,high", "the wind regime|still,breezy,gusty",
         "the demand forecast model|naive,tuned", "the storage capacity|small,large"],
      p=["the peak load on {c}|low,normal,high", "whether a brownout occurs on {c}|brownout,no brownout",
         "the solar output on {c}|weak,strong", "the spot price on {c}|cheap,moderate,expensive"]),
    D(name="archaeology", case="trench", setting="the {X} excavation",
      g=["the site's age|recent,ancient", "the {X} settlement's type|farming,trading,military",
         "the soil preservation|poor,good", "the dig team's skill|novice,expert"],
      p=["the pottery finds in {c}|none,some,many", "whether {c} contains bone|bone,no bone",
         "the stratigraphy of {c}|disturbed,clear", "the coin finds in {c}|none,few,many"]),
    D(name="fashion", case="season launch", setting="the {X} clothing label",
      g=["the lead designer's direction|classic,avant-garde", "the {X} fabric mill's quality|poor,fine",
         "the marketing budget|small,medium,large", "the brand's reputation|niche,mainstream"],
      p=["the critics' verdict on {c}|pan,mixed,rave", "the sales of {c}|weak,strong",
         "whether {c} sells out|sold out,not sold out", "the social media buzz around {c}|quiet,loud"]),
    D(name="traffic", case="rush hour", setting="the city of {X}",
      g=["the roadworks status|none,minor,major", "the signal timing plan|fixed,adaptive",
         "the {X} bridge's condition|restricted,open", "the public transport strike|off,on"],
      p=["the congestion during {c}|light,moderate,heavy", "whether an accident occurs during {c}|accident,no accident",
         "the average speed during {c}|slow,fast", "the bus punctuality during {c}|poor,good"]),
    D(name="marine_biology", case="dive", setting="the {X} reef",
      g=["the reef's bleaching state|healthy,partial,severe", "the {X} current|weak,strong",
         "the parrotfish population|sparse,abundant", "the water temperature trend|cooling,warming"],
      p=["the coral cover seen on {c}|low,medium,high", "whether a reef shark is sighted on {c}|sighted,not sighted",
         "the visibility on {c}|murky,clear", "the fish diversity on {c}|low,high"]),
    D(name="publishing", case="title", setting="the {X} publishing house",
      g=["the editor's taste|literary,commercial", "the {X} imprint's budget|small,large",
         "the distribution deal|regional,national,international", "the cover design team|new,veteran"],
      p=["the sales of {c}|flop,modest,bestseller", "whether {c} wins a prize|prize,no prize",
         "the reviews of {c}|poor,good", "the print run of {c}|short,long"]),
    D(name="manufacturing", case="shift", setting="the {X} assembly plant",
      g=["the {X} robot arm's wear|new,worn,failing", "the supplier batch|good,faulty",
         "the line speed setting|slow,normal,fast", "the maintenance schedule|lax,strict"],
      p=["the output of {c}|low,target,high", "the scrap rate in {c}|low,high",
         "whether the line stops during {c}|stoppage,no stoppage", "the operator fatigue in {c}|low,high"]),
    D(name="politics", case="district poll", setting="the {X} provincial election",
      g=["the {X} party's momentum|falling,flat,rising", "the incumbent's scandal|none,major",
         "the economy's perception|bad,good", "the turnout drive|weak,strong"],
      p=["the vote share in {c}|low,medium,high", "the turnout in {c}|low,high",
         "whether {c} flips|flips,holds", "the undecided share in {c}|small,large"]),
    D(name="wildlife", case="camera-trap week", setting="the {X} forest",
      g=["the {X} lynx population|absent,small,large", "the deer density|low,high",
         "the logging activity|none,active", "the winter severity|mild,harsh"],
      p=["the lynx sightings in {c}|none,one,several", "the deer sightings in {c}|few,many",
         "whether poacher signs appear in {c}|signs,no signs", "the snow cover in {c}|bare,patchy,deep"]),
    D(name="chemistry", case="reaction run", setting="the {X} process lab",
      g=["the catalyst lot|inactive,active,hyperactive", "the reagent purity|low,high",
         "the {X} reactor's seal|leaking,tight", "the operator's protocol|old,revised"],
      p=["the yield of {c}|low,medium,high", "the colour of the product in {c}|clear,cloudy",
         "whether {c} overheats|overheats,stable", "the by-product level in {c}|low,high"]),
    D(name="gaming", case="tournament round", setting="the {X} esports circuit",
      g=["the {X} team's skill tier|bronze,silver,gold", "the patch version|old,new",
         "the team's morale|low,high", "the sponsor's pressure|low,high"],
      p=["the outcome of {c}|loss,win", "the round length of {c}|short,medium,long",
         "whether a comeback happens in {c}|comeback,no comeback", "the viewer count for {c}|low,high"]),
    D(name="insurance", case="claim", setting="the {X} mutual insurer",
      g=["the underwriting standard|loose,strict", "the {X} region's risk level|low,medium,high",
         "the fraud unit's staffing|thin,strong", "the reinsurance treaty|narrow,broad"],
      p=["the size of {c}|small,medium,large", "whether {c} is flagged as fraud|flagged,not flagged",
         "the settlement time of {c}|fast,slow", "whether {c} goes to court|court,no court"]),
    D(name="theatre", case="performance", setting="the {X} repertory theatre",
      g=["the director's approach|traditional,experimental", "the {X} lead actor's form|shaky,solid,stellar",
         "the set budget|small,large", "the rehearsal period|rushed,ample"],
      p=["the audience reaction to {c}|cold,warm,ecstatic", "whether {c} has a technical fault|fault,no fault",
         "the attendance at {c}|sparse,full", "the running time of {c}|short,long"]),
    D(name="meteorology_station", case="balloon launch", setting="the {X} weather station",
      g=["the air mass over {X} Plateau|polar,temperate,tropical", "the jet stream position|north,south",
         "the instrument drift|none,some", "the pressure system|low,high"],
      p=["the humidity reading from {c}|dry,moderate,humid", "the wind shear on {c}|low,high",
         "whether {c} reaches the target altitude|reached,not reached", "the temperature profile of {c}|stable,unstable"]),
    D(name="logistics", case="parcel", setting="the {X} courier depot",
      g=["the depot's sorting system|manual,automated", "the {X} driver pool|thin,full",
         "the weather disruption level|none,moderate,severe", "the IT system|legacy,modern"],
      p=["the delivery of {c}|early,on time,late", "whether {c} is damaged|damaged,intact",
         "the handling steps for {c}|few,many", "whether {c} is misrouted|misrouted,correct route"]),
    D(name="mining", case="shaft inspection", setting="the {X} copper mine",
      g=["the ore grade in {X} seam|low,medium,high", "the ventilation system|weak,strong",
         "the rock stability|unstable,stable", "the crew rotation|long,short"],
      p=["the gas level at {c}|safe,elevated,dangerous", "whether water ingress is found at {c}|ingress,dry",
         "the ore recovered at {c}|little,moderate,much", "the dust at {c}|low,high"]),
    D(name="linguistics", case="recording session", setting="the {X} dialect project",
      g=["the {X} dialect's family|northern,coastal,highland", "the speaker community size|small,large",
         "the influence of the capital|weak,strong", "the field linguist's training|basic,expert"],
      p=["the vowel shift heard in {c}|absent,partial,full", "whether a loanword appears in {c}|loanword,none",
         "the speech tempo in {c}|slow,fast", "the recording quality of {c}|noisy,clean"]),
    D(name="urban_planning", case="neighbourhood review", setting="the {X} city council",
      g=["the zoning policy|restrictive,flexible", "the {X} district's density|low,medium,high",
         "the transit investment|low,high", "the housing demand|soft,hot"],
      p=["the rent change in {c}|falling,flat,rising", "whether {c} gets a new park|new park,no park",
         "the resident satisfaction in {c}|low,high", "the vacancy rate in {c}|low,high"]),
    D(name="veterinary", case="herd check", setting="the {X} valley ranch",
      g=["the {X} fever's presence in the valley|absent,present", "the feed quality|poor,average,rich",
         "the vaccination programme|lapsed,current", "the grazing pressure|light,heavy"],
      p=["the weight gain seen at {c}|low,normal,high", "whether lameness is found at {c}|lameness,none",
         "the milk yield at {c}|low,high", "the coat condition at {c}|dull,glossy"]),
    D(name="space_ops", case="orbit pass", setting="the {X} satellite constellation",
      g=["the {X} satellite's battery health|degraded,nominal", "the solar activity|quiet,active,storm",
         "the ground station network|sparse,dense", "the firmware build|old,patched"],
      p=["the downlink quality on {c}|poor,fair,good", "whether a reset occurs on {c}|reset,no reset",
         "the data volume on {c}|small,large", "the thermal reading on {c}|cold,nominal,hot"]),
    D(name="restaurant", case="dinner service", setting="the {X} bistro",
      g=["the head chef's form|off,good,inspired", "the {X} fish supplier|unreliable,reliable",
         "the staffing|short,full", "the menu style|simple,elaborate"],
      p=["the guest rating of {c}|poor,fair,excellent", "whether a dish is sent back in {c}|sent back,none",
         "the covers served in {c}|few,many", "the ticket times in {c}|quick,slow"]),
    D(name="pharma", case="trial cohort", setting="the {X} biotech trial",
      g=["the compound's true efficacy|none,modest,strong", "the dosing regimen|low,high",
         "the {X} site's protocol adherence|poor,good", "the placebo response level|low,high"],
      p=["the symptom improvement in {c}|none,some,large", "whether an adverse event occurs in {c}|adverse event,none",
         "the dropout rate in {c}|low,high", "the biomarker response in {c}|flat,raised"]),
    D(name="forestry", case="stand survey", setting="the {X} timber concession",
      g=["the {X} beetle infestation|none,light,heavy", "the soil fertility|poor,rich",
         "the thinning regime|none,regular", "the fire history|unburnt,burnt"],
      p=["the tree growth in {c}|slow,normal,fast", "whether dead trees are found in {c}|dead trees,none",
         "the canopy cover in {c}|open,closed", "the undergrowth in {c}|sparse,dense"]),
    D(name="cybersecurity", case="login attempt", setting="the {X} company network",
      g=["the attacker's presence|none,opportunistic,targeted", "the password policy|weak,strong",
         "the {X} firewall's configuration|misconfigured,sound", "the staff awareness|low,high"],
      p=["the origin of {c}|domestic,foreign", "whether {c} fails|failed,succeeded",
         "the time of {c}|office hours,night", "whether {c} triggers an alert|alert,no alert"]),
    D(name="brewing", case="brew", setting="the {X} brewery",
      g=["the {X} yeast strain's health|stressed,healthy", "the malt quality|poor,standard,premium",
         "the water hardness|soft,medium,hard", "the cellar temperature control|loose,tight"],
      p=["the gravity of {c}|low,target,high", "the clarity of {c}|hazy,clear",
         "whether {c} develops off-flavours|off-flavours,clean", "the carbonation of {c}|flat,lively"]),
    D(name="real_estate", case="viewing", setting="the {X} estate agency",
      g=["the property's true condition|poor,fair,excellent", "the {X} neighbourhood's appeal|low,high",
         "the asking price strategy|low,market,high", "the mortgage climate|tight,easy"],
      p=["the viewer interest at {c}|low,high", "whether {c} leads to an offer|offer,no offer",
         "the survey remarks after {c}|few,many", "the viewer's impression at {c}|negative,neutral,positive"]),
    D(name="orchestra_tour", case="tour stop", setting="the {X} touring company",
      g=["the tour manager's competence|weak,strong", "the {X} bus fleet's reliability|poor,good",
         "the booking agent's reach|local,national", "the company's cohesion|fraying,tight"],
      p=["the audience size at {c}|small,medium,large", "whether {c} starts late|late,on time",
         "the local press coverage of {c}|none,some", "the merchandise sales at {c}|low,high"]),
    D(name="water_utility", case="sample", setting="the {X} water authority",
      g=["the {X} reservoir's contamination|clean,trace,contaminated", "the treatment plant status|degraded,normal",
         "the pipe network age|new,old", "the rainfall runoff|low,high"],
      p=["the turbidity of {c}|clear,cloudy", "the bacteria count in {c}|none,low,high",
         "whether {c} fails the chlorine test|fails,passes", "the taste complaint linked to {c}|none,complaint"]),
]
assert len(DOMAINS) >= 40, len(DOMAINS)


def parse_concept(s: str):
    np_, states = s.split("|")
    return np_, states.split(",")


def instantiate(rng, concept: str):
    np_, states = parse_concept(concept)
    return np_.replace("{X}", pseudo(rng)), states
