"""Table domains: realistic column schemas for tickets, patients, transactions, sensor logs, sales, web access logs,
shipments, HR records and bug reports.

Column specs
  ("cat", name, [values])                         categorical (values contain no spaces, commas or '|')
  ("num", name, dict(lo, hi, mu, sigma, dec, log, cuts))
        drawn from a (log)normal around mu, clipped to [lo, hi], rounded to `dec` decimals;
        `cuts` are candidate bucket edges used when the column is queried (bucket = [edge_i, edge_i+1))
Every domain has an id column pattern, an entity noun, a timestamp column name and framing sentences.
"""
from __future__ import annotations

D = dict

DOMAINS = [
    D(name="tickets", ent="ticket", ents="tickets", id_col="ticket_id", id_fmt="T-{n}", time_col="created_at",
      log_level=True,
      cols=[("cat", "region", ["north", "south", "east", "west"]),
            ("cat", "channel", ["email", "phone", "chat", "web"]),
            ("cat", "priority", ["low", "medium", "high", "urgent"]),
            ("cat", "category", ["billing", "login", "bug", "shipping", "refund"]),
            ("cat", "status", ["open", "resolved", "escalated"]),
            ("cat", "tier", ["free", "pro", "enterprise"]),
            ("num", "first_response_min", D(lo=1, hi=600, mu=45, sigma=0.9, dec=0, log=True, cuts=[15, 30, 60, 120, 240])),
            ("num", "csat", D(lo=1, hi=5, mu=3.6, sigma=1.1, dec=0, log=False, cuts=[3, 4, 5]))],
      framing=["Below is an export of support tickets from the helpdesk.",
               "A customer-support team shared this ticket log.",
               "Here are support tickets pulled from the ticketing system."]),
    D(name="patients", ent="patient", ents="patients", id_col="patient_id", id_fmt="P{n}", time_col="admitted_at",
      log_level=False,
      cols=[("cat", "ward", ["cardio", "ortho", "neuro", "general"]),
            ("cat", "sex", ["F", "M"]),
            ("cat", "smoker", ["yes", "no"]),
            ("cat", "bp_category", ["normal", "elevated", "high"]),
            ("cat", "readmitted", ["yes", "no"]),
            ("cat", "insurance", ["public", "private", "none"]),
            ("num", "age", D(lo=18, hi=95, mu=56, sigma=17, dec=0, log=False, cuts=[40, 50, 65, 75])),
            ("num", "length_of_stay_days", D(lo=1, hi=40, mu=4, sigma=0.7, dec=0, log=True, cuts=[3, 5, 7, 10]))],
      framing=["The following is a de-identified extract of hospital admissions.",
               "A clinic analyst exported these patient records.",
               "Here is a table of admissions from a regional hospital."]),
    D(name="transactions", ent="transaction", ents="transactions", id_col="txn_id", id_fmt="tx_{n}", time_col="ts",
      log_level=True,
      cols=[("cat", "merchant_category", ["grocery", "travel", "electronics", "dining", "fuel"]),
            ("cat", "card_type", ["debit", "credit", "prepaid"]),
            ("cat", "channel", ["online", "in-store"]),
            ("cat", "country", ["domestic", "foreign"]),
            ("cat", "flagged", ["yes", "no"]),
            ("cat", "chargeback", ["yes", "no"]),
            ("num", "amount", D(lo=1, hi=5000, mu=60, sigma=1.1, dec=2, log=True, cuts=[20, 50, 100, 250, 500]))],
      framing=["These are card transactions from a payments processor.",
               "A fraud analyst is looking at this batch of transactions.",
               "Here is a transaction log exported from the ledger."]),
    D(name="sensors", ent="reading", ents="readings", id_col="reading_id", id_fmt="r{n}", time_col="timestamp",
      log_level=True,
      cols=[("cat", "device", ["sensor-01", "sensor-02", "sensor-03", "sensor-04"]),
            ("cat", "zone", ["A", "B", "C"]),
            ("cat", "status", ["OK", "WARN", "FAIL"]),
            ("cat", "battery", ["low", "ok"]),
            ("cat", "door", ["open", "closed"]),
            ("num", "temp_c", D(lo=-10, hi=60, mu=22, sigma=6, dec=1, log=False, cuts=[15, 20, 25, 30])),
            ("num", "humidity_pct", D(lo=5, hi=100, mu=48, sigma=14, dec=0, log=False, cuts=[30, 40, 50, 60, 70]))],
      framing=["The building-management system logged these sensor readings.",
               "Here are raw readings from an IoT sensor network.",
               "A facilities engineer pulled this sensor log."]),
    D(name="sales", ent="order", ents="orders", id_col="order_id", id_fmt="SO-{n}", time_col="order_date",
      log_level=False,
      cols=[("cat", "region", ["EMEA", "APAC", "AMER"]),
            ("cat", "product_line", ["hardware", "software", "services", "support"]),
            ("cat", "segment", ["smb", "mid-market", "enterprise"]),
            ("cat", "discount", ["0%", "10%", "20%"]),
            ("cat", "returned", ["yes", "no"]),
            ("cat", "payment", ["card", "invoice", "wire"]),
            ("num", "units", D(lo=1, hi=200, mu=8, sigma=0.9, dec=0, log=True, cuts=[3, 5, 10, 20, 50])),
            ("num", "revenue_usd", D(lo=10, hi=90000, mu=1800, sigma=1.0, dec=0, log=True, cuts=[500, 1000, 2500, 5000, 10000]))],
      framing=["This is an export of the order book from the sales CRM.",
               "A revenue-operations analyst exported these orders.",
               "Here is a list of closed sales orders."]),
    D(name="web", ent="request", ents="requests", id_col="req_id", id_fmt="q{n}", time_col="time",
      log_level=True,
      cols=[("cat", "method", ["GET", "POST", "PUT"]),
            ("cat", "path", ["/api/login", "/api/cart", "/api/search", "/static/app.js"]),
            ("cat", "status", ["200", "302", "404", "500"]),
            ("cat", "cache", ["HIT", "MISS"]),
            ("cat", "client", ["mobile", "desktop", "bot"]),
            ("num", "latency_ms", D(lo=1, hi=5000, mu=90, sigma=1.0, dec=0, log=True, cuts=[50, 100, 250, 500, 1000])),
            ("num", "bytes", D(lo=100, hi=900000, mu=12000, sigma=1.2, dec=0, log=True, cuts=[2000, 10000, 50000]))],
      framing=["These lines come from a web server's access log.",
               "An SRE is investigating this slice of HTTP request logs.",
               "Here is a sample of requests recorded by the load balancer."]),
    D(name="shipments", ent="shipment", ents="shipments", id_col="shipment_id", id_fmt="SH{n}", time_col="shipped_at",
      log_level=False,
      cols=[("cat", "carrier", ["Norvik", "Altamira", "Pellucid", "Kestrel"]),
            ("cat", "service", ["standard", "express", "overnight"]),
            ("cat", "origin_hub", ["hub-1", "hub-2", "hub-3"]),
            ("cat", "delayed", ["yes", "no"]),
            ("cat", "damaged", ["yes", "no"]),
            ("cat", "signature", ["required", "not-required"]),
            ("num", "weight_kg", D(lo=0.1, hi=70, mu=3, sigma=0.9, dec=1, log=True, cuts=[1, 2, 5, 10, 20])),
            ("num", "transit_days", D(lo=1, hi=14, mu=3, sigma=0.5, dec=0, log=True, cuts=[2, 3, 5, 7]))],
      framing=["A logistics team exported these shipment records.",
               "Here is a shipment tracking table from the warehouse system.",
               "The following shipments were dispatched from the warehouse."]),
    D(name="hr", ent="employee", ents="employees", id_col="emp_id", id_fmt="E{n}", time_col="last_review",
      log_level=False,
      cols=[("cat", "department", ["engineering", "sales", "support", "finance"]),
            ("cat", "level", ["junior", "mid", "senior"]),
            ("cat", "remote", ["yes", "no"]),
            ("cat", "left_company", ["yes", "no"]),
            ("cat", "rating", ["below", "meets", "exceeds"]),
            ("num", "tenure_years", D(lo=0, hi=30, mu=4, sigma=0.8, dec=1, log=True, cuts=[1, 2, 5, 10])),
            ("num", "salary_k", D(lo=30, hi=400, mu=95, sigma=0.35, dec=0, log=True, cuts=[60, 80, 100, 130, 180]))],
      framing=["These are anonymised employee records from the HR system.",
               "A people-analytics team shared this staff table.",
               "Here is an HR export of current and former employees."]),
    D(name="bugs", ent="bug", ents="bugs", id_col="bug_id", id_fmt="BUG-{n}", time_col="opened",
      log_level=True,
      cols=[("cat", "component", ["ui", "api", "db", "auth", "infra"]),
            ("cat", "severity", ["minor", "major", "critical"]),
            ("cat", "found_by", ["qa", "customer", "monitoring"]),
            ("cat", "regression", ["yes", "no"]),
            ("cat", "state", ["open", "fixed", "wontfix"]),
            ("num", "triage_days", D(lo=0, hi=365, mu=12, sigma=1.0, dec=0, log=True, cuts=[3, 7, 14, 30, 90])),
            ("num", "comments", D(lo=0, hi=80, mu=5, sigma=0.8, dec=0, log=True, cuts=[2, 5, 10, 20]))],
      framing=["Here is an export from the team's bug tracker.",
               "An engineering manager pulled these bug reports.",
               "The following issues were filed against the product."]),
]
